### ISSUE TITLE
gltf export

### ISSUE THREAD

**Issue by zignig** [CadQuery/pywrap#12]
OCP 7.4.0 has Glft  export. 

https://tracker.dev.opencascade.org/view.php?id=30953

How would I go about adding this functionality to the OCP bindings ?

**Comment by adam-urbanczyk** [comment]
It is actually in the unreleased OCCT 7.5. Once it is released I will updated the bindings.

If you want to try pywrap out: prepare correct env (see the env file), edit the input file (see `ocp.toml`), run the generator (see run.sh) and finally compile using CMake. Usually few iterations of editing the toml input will be needed.

**Comment by zignig** [comment]
Seems to be in 7.4.0 ...

https://git.dev.opencascade.org/gitweb/?p=occt.git;a=tree;f=src/RWGltf;h=6586f6f7497865ec18d8e0403481a6f41437614a;hb=fd47711d682be943f0e0a13d1fb54911b0499c31

Will investigate running pywrap anyway so I can get up to speed on how it works.

**Comment by adam-urbanczyk** [comment]
I will close this and open a similar issue in the OCP tracker.
