### ISSUE TITLE
[FR] rename: OCP -> pyocct

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [CadQuery/pywrap#13]
after spending some time with CQ I still stumble upon "OCT" name every time

please consider `pyocct` instead:

https://anaconda.org/search?q=occt

https://github.com/LaughlinResearch/pyOCCT

**Comment by jmwright** [comment]
I spent some time with PyOCCT awhile back. It appears that the original developer doesn't have time to work on it now, and the bindings Adam is working on use newer tech.

You'll come across "OCCT," "OCE" and sometimes "OCT" while searching this area. OCCT is the name of the core CAD kernel all of us use, and there are variations on that name around.

**Comment by Andrei-Pozolotin** [comment]
well, one of these initiatives
https://github.com/CadQuery/cadquery/issues/310
https://github.com/LaughlinResearch/pyOCCT/issues/30

is bound to become obsolete, 
therefore `pyocct` is a good name to keep here for `CQ` as well :-)

**Comment by adam-urbanczyk** [comment]
@Andrei-Pozolotin let's not spend time on naming discussions. OCP is a name that was free and I don't think that changing it to a name of another project will help anyone. Let's say it stands for _OpenCascade for Python_

As @jmwright mentioned: 
* CAD kernel names: OCCT ~ OpenCascade (older name I think) ~ OCE (obsolete fork of OCCT)
* Various bindings:
    * PythonOCC
    * PythonOCCT
    * OCP
