### ISSUE TITLE
Cannot Build Conda Environment

### ISSUE THREAD

**Issue by jmwright** [CadQuery/pywrap#3]
The error I get is that the `system` package version required is not found.
```
$ conda env create -f ./env.yml -n pywrap
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - system==5.8=2
```
I'm running Ubuntu 18.04 64-bit. Below is some Anaconda info. It is the Anaconda 2019.10 version.
```
$ conda list anaconda$
# packages in environment at /home/jwright/anaconda3:
#
# Name                    Version                   Build  Channel
anaconda                  custom                   py37_1
```

**Comment by adam-urbanczyk** [comment]
It is available in the `anaconda` channel:

anaconda/system           |      5.8 | conda           | linux-64, linux-32

**Comment by jmwright** [comment]
Looks like it's available via this:
```
conda install -c anaconda system
```
https://anaconda.org/anaconda/system

I can install it manually after adding that. However, I'm having trouble getting the equivalent to work in env.yml. I'm still learning Anaconda, so I'm not sure what I'm doing wrong.

**Comment by jmwright** [comment]
Ok, I misunderstood. By adding the `anaconda` channel at the top of the env.yml file I was able to build the environment. I'm not sure if this is a quirk with my Anaconda installation or if it's something that needs to be added to the yaml file here in the repo.
