### ISSUE TITLE
wrapping fails unless CONDA_PREFIX is set

### ISSUE THREAD

**Issue by greyltc** [CadQuery/pywrap#31]
https://github.com/CadQuery/pywrap/blob/367eb8de984344d3a7cde85b3bef6c5d2c1092c9/bindgen/utils.py#L56

**Comment by adam-urbanczyk** [comment]
Solved by https://github.com/CadQuery/pywrap/commit/420c92f56d2d8bb416744a11fd078cddf6cec8be

**Comment by greyltc** [comment]
thanks!
