### ISSUE TITLE
Embed cymbal [Which cymbal should be used?]

### ISSUE THREAD

**Issue by nealie** [CadQuery/pywrap#37]
I'm still working on getting a port of CadQuery updated on FreeBSD using it's own pywrap generated code, which requires that everything that pywrap needs is also ported if not already present. In this case it's cymbal I'm working on.

Should I be using the cymbal code present in the PyPI or the CadQuery branch? I have based my port on the former so far, but the unit tests fail when it tried to monkey patch code where there is already code. Everything works and OCP seems to be generated properly, but the port will not be accepted if the tests fail and I do not have a good explanation why.

**Comment by marcus7070** [comment]
Tests for cymbal fail for me too. I just don't run the tests.

```
python3.8-cymbal-git> test_class_template_args (tests.test_clang_extensions.TestClangExtension) ... ERROR
python3.8-cymbal-git> test_fails_to_add (tests.test_clang_extensions.TestClangExtension) ... ok
python3.8-cymbal-git> ======================================================================
python3.8-cymbal-git> ERROR: test_class_template_args (tests.test_clang_extensions.TestClangExtension)
python3.8-cymbal-git> ----------------------------------------------------------------------
python3.8-cymbal-git> Traceback (most recent call last):
python3.8-cymbal-git>   File "/build/source/tests/test_clang_extensions.py", line 25, in test_class_template_args
python3.8-cymbal-git>     cymbal.monkeypatch_type('get_template_argument_type',
python3.8-cymbal-git>   File "/build/source/cymbal/clangext.py", line 24, in monkeypatch_type
python3.8-cymbal-git>     monkeypatch_helper(clang.cindex.Type, method_name, library_function, args, result)
python3.8-cymbal-git>   File "/build/source/cymbal/clangext.py", line 15, in monkeypatch_helper
python3.8-cymbal-git>     raise CymbalException('failed to add method, %s is already available' % name)
python3.8-cymbal-git> cymbal.clangext.CymbalException: failed to add method, get_template_argument_type is already available
python3.8-cymbal-git> ----------------------------------------------------------------------
python3.8-cymbal-git> Ran 2 tests in 0.000s
python3.8-cymbal-git> FAILED (errors=1)
python3.8-cymbal-git> Test failed: <unittest.runner.TextTestResult run=2 errors=1 failures=0>
python3.8-cymbal-git> error: Test failed: <unittest.runner.TextTestResult run=2 errors=1 failures=0>
```

**Comment by adam-urbanczyk** [comment]
https://github.com/CadQuery/pywrap/blob/e8c7bc915f9a1f9711608e46ccc6212239f4ac98/env.yml#L20 pypi version is used

**Comment by nealie** [comment]
This is what I feared. I had better pass the pain upstream then.

**Comment by adam-urbanczyk** [comment]
Looks unmaintained. If it's _that_ much of a problem I could just incorporate the relevant part of the code into pywrap.

**Comment by nealie** [comment]
It's certainly a problem for me. Firstly it means that I had to write an extra FreeBSD port for the pywrap port to use, but QA has required me to make use of the tests in Cymbal, which currently fail. This may mean that I can't get the port committed, thus stalling the whole process of upgrading the CadQuery port, which has taken an insanely long amount of time for me to get done so far.

If you could subsume the needed code I would be very grateful and since it's unmaintained it might be better for your future maintainability anyway ;-).

**Comment by adam-urbanczyk** [comment]
OK, reopening to track this.
