### ISSUE TITLE
Changes in ocp.toml for 7.7.0 compatibility

### ISSUE THREAD

**Issue by kiufta** [CadQuery/pywrap#47]
As you already know through https://github.com/CadQuery/OCP/issues/94 I'm trying to ease your workload and make https://github.com/CadQuery/pywrap/blob/master/ocp.toml compatible for use with current git master https://github.com/Open-Cascade-SAS/OCCT which will become 7.7.0

How do you usually regenerate the TOML config?

**Comment by adam-urbanczyk** [comment]
It is not generated, it is written by hand. No help on 7.7 needed ATM.
