### ISSUE TITLE
gp.toml Has Hardcoded Path In It

### ISSUE THREAD

**Issue by jmwright** [CadQuery/pywrap#5]
The `input_folder` variable in gp.toml is hard coded to a user-specific path. I haven't been able to get the `USER` environment variable to work in the toml file yet, but am out of time for now. I'll try to circle back to this later today.

I also noticed that `anaconda2` is used in the path, and only `anaconda3` is available on my system.

**Comment by adam-urbanczyk** [comment]
I would not say it is hardcoded - you need to point the tool to the location with OCCT headers. 

The name of the folder is not really relevant (I happen to have my anaconda installed in a local folder called `anaconda2`)

**Comment by jmwright** [comment]
How do I point it to the right place? Is there a way to override what's in go.yoml by passing an option? https://github.com/CadQuery/pywrap/blob/master/gp.toml#L2

**Comment by adam-urbanczyk** [comment]
Just edit the file - it is meant to be edited. In the end I will split this repo into two. One for the bindgen code and the other for OCCT binding related stuff (it will include the conf file in question).

**Comment by jmwright** [comment]
Ok, got it. Thanks.

**Comment by adam-urbanczyk** [comment]
I added the OCCT headers for now - it should be now easier to build locally.
